#!/usr/bin/env bash

# Generate: A command-line script file generation tool written in bash 5.2+.
# https://github.com/membersincewayback/gen
#
# Copyright (C) 2022 Zac Piatt
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version="Generate (gen) version: 1.0"

usage() {
cat << EOF
Usage: gen [OPTION]... [FILE]...
Generate FILE, auto-input typical text, and auto-launch default editor.

  -e,   select editor ( gen -e nano test.txt )
  -s,   suppress auto-launch of editor
  -h,   display this help and exit
  -v,   display version number and exit

Full documentation <https://github.com/membersincewayback/gen>
${version}
EOF
exit
}

check_ext() {
    case "$1" in
        *.py ) touchpy >> "$1" ;;
        *.pl ) chmod u+x "$1"; touchpl >> "$1"; line=4 ;;
        *.c ) touchc >> "$1"; line=4 ;;
        *.sh|*.bash ) chmod u+x "$1"; ext="bash"; touchsh >> "$1" ;;
        *.ksh ) chmod u+x "$1"; ext="ksh"; touchsh  >> "$1"; ;;
        *.csh ) chmod u+x "$1"; ext="csh"; touchsh  >> "$1"; ;;
        *.awk ) chmod u+x "$1"; ext="awk"; touchsh  >> "$1"; ;;
        *.js ) chmod u+x "$1"; ext="js"; touchjs >> "$1"; ;;
        *.html|*.htm ) touchhtml >> "$1" ;;
        * ) return ;;
    esac
}

get_args() {
while getopts 'e:shv' OPTION; do
    case $OPTION in
        e) EDITOR=$OPTARG ;;
        s) suppress="True" ;;
        h) usage ;;
        v) echo "${version}"; exit ;;
        ?) usage ;;
    esac
done
}

exists() {
    if [[ -e "$1" ]]; then
        echo "Filename already exists."
        exit
    else
        if ! touch "$1"; then
            usage
        fi
    fi
}

main() {
    if [[ -f templates ]]; then
        source templates
    fi
    get_args "$@"
    exists "${@: -1}"
    check_ext "${@: -1}"
    [[ ! ${suppress} ]] && ${EDITOR:-vi} +"${line:-2}" "${@: -1}"
}

main "$@"
