#!/usr/bin/env bash

printf "Generate (gen) v1.2 installer.\n"

TARGET_DIR="${HOME}"/.gen

install() {
    if [[ ! -d  ${TARGET_DIR} ]]; then
        mkdir -p "${TARGET_DIR}"
        git clone https://github.com/membersincewayback/gen.git "${TARGET_DIR}"
    fi
    sudo ln -s "${TARGET_DIR}"/gen /usr/bin/gen
    chmod +x "${TARGET_DIR}"/gen "${TARGET_DIR}"/install
}

uninstall() {
    sudo rm -r /usr/bin/gen
    rm -rf "${TARGET_DIR}"
}

update() {
    (cd ${HOME}/.gen && git pull)
}

case "$1" in
    install) install ;;
    uninstall) uninstall ;;
    update) update ;;
esac
