#!/usr/bin/env bash

echo -e "\e[1mUSAGE: run install to install and install uninstall to uninstall.\e[0m"

TARGET_DIR="${HOME}"/.gen

install() {
    if [[ ! -d  "${TARGET_DIR}" ]]; then
        mkdir -p "${TARGET_DIR}"
        git clone https://github.com/membersincewayback/gen.git "${TARGET_DIR}"
    fi
    sudo ln -s "${TARGET_DIR}"/gen /usr/bin/gen
    chmod +x "${TARGET_DIR}"/gen
    chmod +x "${TARGET_DIR}"/install
}

uninstall() {
    sudo rm -r /usr/bin/gen
    rm -rf "${TARGET_DIR}"
}

if [[ "$1" == "uninstall" ]]; then
    uninstall
else
    install
fi

