#!/bin/env bash

touchpy() {
cat << EOF
def main():

if __name__ == '__main__':
    main()
EOF
}

touchpl() {
cat << EOF
#!/usr/bin/perl
use strict;
use warnings;

EOF
}

touchc() {
cat << EOF
#include <stdio.h>

int main()
{
   return 0;
}
EOF
}

touchsh() {
cat << EOF
#!/usr/bin/env ${ext}
EOF
}

touchjs() {
cat << EOF
#!/usr/bin/env node

EOF
}

touchhtml() {
cat << EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HTML 5 Boilerplate</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
        <script src="index.js"></script>
  </body>
</html>
EOF
}
