#!/bin/env bash

template="$(< "${TEMPLATES}")"

touchpy() {
cat <<[-]EOF
${template}
[-]EOF
}

touchpl() {
cat <<[-]EOF
${template}
[-]EOF
}

touchc() {
cat <<[-]EOF
${template}
[-]EOF
}

touchsh() {
cat <<[-]EOF
${template}
[-]EOF
}

touchhtml() {
cat <<[-]EOF
${template}
[-]EOF
}
